development:
    - username: <development_username>,
    - password: '<development_password>',
    - database: '<development_database_name>',
    - host: '127.0.0.1', // or, localhost
    - port: '5432',
    # - dialect: 'postgres',
        # - host: '/tmp/.s.PGSQL.5432'
        # - host: `/var/run/postgresql/.s.PGSQL.5432`
        # - dialectOptions:
        # - socketPath: '/var/run/postgresql/.s.PGSQL.5432'

test:
    - username: <development_username>,
    - password: '<development_password>',
    - database: '<development_database_name>',
    - host: '127.0.0.1', // or, localhost
    - port: '5432',
    # - dialect: 'postgres',
        # - host: '/tmp/.s.PGSQL.5432'
        # - host: `/var/run/postgresql/.s.PGSQL.5432`
        # - dialectOptions:
        # - socketPath: '/var/run/postgresql/.s.PGSQL.5432'

production:
    - username: <development_username>,
    - password: '<development_password>',
    - database: '<development_database_name>',
    - host: '127.0.0.1', // or, localhost
    - port: '5432',
    # - dialect: 'postgres',
        # - host: '/tmp/.s.PGSQL.5432'
        # - host: `/var/run/postgresql/.s.PGSQL.5432`
        # - dialectOptions:
        # - socketPath: '/var/run/postgresql/.s.PGSQL.5432'